[workspace]
members = [
    "crates/aggregate_public_keys",
    "crates/decrypt_one_layer",
    "crates/gen_elgamal_key_pair",
    "crates/shared",
    "crates/shuffle4",
    "crates/shuffle5",
    "crates/shuffle6",
    "crates/shuffle7",
    "crates/shuffle8",
    "crates/shuffle9",
    "crates/shuffle10",
    "crates/verify_card_message"
]
