g      = "3"
pk_agg = "17"
deck = [
  ["1", "10"],
  ["1", "20"],
  ["1", "30"],
  ["1", "40"],
]
rand = ["77", "88", "99", "111"]
perm = [
  ["1", "0", "0", "0"],
  ["0", "1", "0", "0"],
  ["0", "0", "1", "0"],
  ["0", "0", "0", "1"],
]
