g      = "3"
agg_pk = "17"
deck = [
  ["1", "10"],
  ["1", "20"],
  ["1", "30"],
  ["1", "40"],
  ["1", "50"],
  ["1", "60"],
  ["1", "70"],
  ["1", "80"],
]
rand = ["77", "88", "99", "111", "222", "333", "444", "555"]
perm = [
  ["1", "0", "0", "0", "0", "0", "0", "0"],
  ["0", "1", "0", "0", "0", "0", "0", "0"],
  ["0", "0", "1", "0", "0", "0", "0", "0"],
  ["0", "0", "0", "1", "0", "0", "0", "0"],
  ["0", "0", "0", "0", "1", "0", "0", "0"],
  ["0", "0", "0", "0", "0", "1", "0", "0"],
  ["0", "0", "0", "0", "0", "0", "1", "0"],
  ["0", "0", "0", "0", "0", "0", "0", "1"],
]
